### ISSUE TITLE
art-af issues

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/lei-8906-ownpt#36]
obrigando obrigar VMG0000 1 - 4 synsets below
apresentá apresentar VMN0000 1 -
quinze_dias quinze_dias NCMP000 1 - not mwe?
prorrogável prorrogável AQ0CS00 1 - really missing

1.02560424-v impose, enforce | impor, obrigar (compel to behave in a certain way; "Social relations impose courtesy")
2.02506546-v oblige, obligate, compel | forçar, obrigar, compelir, constranger (force somebody to do something; "We compel all students to fill out this form")
3. 02504562-v squeeze, coerce, pressure, force, hale | forçar, compelir, obrigar
(to cause to do through pressure or necessity, by physical, moral or intellectual means :"She forced him to take a job in the city"; "He squeezed her for information")
4.00885217-v obligate, bind, hold, oblige | obrigar, prender, vincular
 (bind by an obligation; cause to be indebted; "He's held by a contract"; "I'll hold you by your promise")

apresentar has 15 different synsets, why nothign is showing?

**Comment by vcvpaiva** [comment]
suggestion for prorrogável: extendable, renewable
https://www.linguee.com.br/portugues-ingles/traducao/prorrog%C3%A1vel.html

**Comment by arademaker** [comment]
Estou entendendo que erros de FL foram dois:

1. quinze dias
2. Nenhum sense de “apresentar” não ser sido em encontrado.

**Comment by arademaker** [comment]
Primeiro caso resolvido, tinha uma entrada no data/pt/locucions.dat que juntava os tokens quinze_dias, não sei a motivação para isso, não me parece razoável, então removi. Vide novo art-af.out no 205b15a.

**Comment by arademaker** [comment]
Caso de apresentar eu reportei para o Padro.

**Comment by vcvpaiva** [comment]
a motivacao 'e que tem uma palavra unica pra quinze_dias tanto em ingles (fortnight) quanto em frances (eu acho). mas sim, nao 'e mwe em portugues, apesar de bem usada..

continuamos com o problema do  "obrigar" que FL tb nao esta' achando nenhum resultado.
prorrogavel 'e problema nosso mesmo.

**Comment by arademaker** [comment]
Não entendi, FL achou sim. Para `obrigar/V` temos

```
obrigado obrigar VMP00SM 0.323248 02627934-v:0.00182527/02504562-v:0.00166799/02506546-v:0.00164697/00885217-v:0.0016069/02560424-v:0.00157205/01146732-a:0.00155968/01616891-a:0.00153745/00848466-a:0.0015153
```

**Comment by vcvpaiva** [comment]
Bom, quando eu olho em 
https://github.com/own-pt/lei-8906-ownpt/blob/master/freeling/art-af.out
eu vejo (linhas 28-33):

procuração procuração NCFS000 1 06530789-n:0.00299854/06531141-n:0.00222492
, , Fc 1 -
obrigando obrigar VMG0000 1 -
se se PP3CN00 1 -
a a SP 0.313151 -
apresentá apresentar VMN0000 1 -

tanto obrigar qto a presentar nao tem synset????

**Comment by arademaker** [comment]
Como disse, estes casos parecem bugs do FL que reportei ao Padro. Também não entendi porque ele não está achando `apresentar` e `obrigar` , ambos existem no senses30.src que é produzido a partir da OWN-PT.

**Comment by vcvpaiva** [comment]
ok, por mim esse podemos fechar, se colocamarmos:
1. apresentar e obrigar na conta do Padro
2. prorrogável: extendable, renewable
https://www.linguee.com.br/portugues-ingles/traducao/prorrog%C3%A1vel.html
01962982-a
01434530-a
na nossa conta (ja' foram sugeridos e teem dois votos).
